# Generated by Django 5.1.6 on 2025-02-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ticker_text',
            field=models.TextField(blank=True, help_text='Каждое слово или фраза с новой строки', verbose_name='Текст бегущей строки'),
        ),
    ]
