# Generated by Django 5.1.6 on 2025-02-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_ticker_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст бегущей строки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Бегущая строка брендов',
                'verbose_name_plural': 'Бегущие строки брендов',
                'ordering': ['order'],
            },
        ),
    ]
