# Generated by Django 5.0.6 on 2025-02-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brandticker_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_hero', models.BooleanField(default=True, verbose_name='Показывать Hero секцию')),
                ('show_ticker', models.BooleanField(default=True, verbose_name='Показывать бегущую строку')),
            ],
            options={
                'verbose_name': 'Настройки страницы брендов',
                'verbose_name_plural': 'Настройки страницы брендов',
            },
        ),
    ]
