# Generated by Django 5.1.6 on 2025-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_brandspagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('cover_image', models.ImageField(upload_to='album_covers/', verbose_name='Обложка')),
                ('yandex_folder', models.CharField(max_length=200, verbose_name='Папка на Яндекс.Диске')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ['-date'],
            },
        ),
    ]
