# Generated by Django 5.1.6 on 2025-02-07 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_photoalbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoalbum',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.city', verbose_name='Город'),
        ),
    ]
