# Generated by Django 5.1.6 on 2025-02-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_photoalbum_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoalbum',
            name='yandex_folder',
            field=models.CharField(help_text='Укажите путь к папке на Яндекс.Диске (например: Photos/Events/2024)', max_length=200, verbose_name='Папка на Яндекс.Диске'),
        ),
    ]
