# Generated by Django 5.1.6 on 2025-02-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_photoalbum_yandex_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='yandex_token',
            field=models.CharField(blank=True, default='', help_text='OAuth токен для доступа к Яндекс.Диску', max_length=200, verbose_name='Токен Яндекс.Диска'),
        ),
    ]
