# Generated by Django 5.1.6 on 2025-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_photoalbum_yandex_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_token', models.CharField(help_text='OAuth токен для доступа к Яндекс.Диску', max_length=200, verbose_name='Токен Яндекс.Диска')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='yandex_token',
        ),
    ]
