# Generated by Django 5.0.6 on 2025-02-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_photoalbum_options_photoalbum_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoalbum',
            options={'ordering': ['-date'], 'verbose_name': 'Фотоальбом', 'verbose_name_plural': 'Фотоальбомы'},
        ),
        migrations.RemoveIndex(
            model_name='photoalbum',
            name='main_photoa_city_id_67639d_idx',
        ),
        migrations.RemoveIndex(
            model_name='photoalbum',
            name='main_photoa_is_publ_ea9033_idx',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='order',
        ),
    ]
