# Generated by Django 5.0.6 on 2025-02-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, help_text='Текст для секции "О нас"', verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Контактный email', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gis_link',
            field=models.URLField(blank=True, help_text='Полный URL вашей компании на 2GIS', verbose_name='Ссылка на 2GIS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Полный URL вашего Instagram аккаунта', verbose_name='Ссылка на Instagram'),
        ),
    ]
