# Generated by Django 5.0.6 on 2025-02-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sitesettings_about_text_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1920x1080px', null=True, upload_to='about/', verbose_name='Изображение для секции "О нас"'),
        ),
    ]
