# Generated by Django 5.0.6 on 2025-02-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sitesettings_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='gis_link',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_link',
            field=models.URLField(blank=True, help_text='Полный URL вашего TikTok аккаунта', verbose_name='Ссылка на TikTok'),
        ),
    ]
