# Generated by Django 5.0.6 on 2025-02-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_sitesettings_gis_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Анонс', 'verbose_name_plural': 'Анонсы'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='header',
            field=models.TextField(blank=True, help_text='Например: "Готовимся к захватывающему событию: уже [дата] мы ждем вас на [название мероприятия]"', verbose_name='Заголовок анонса'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('event', 'Событие'), ('promo', 'Акция'), ('news', 'Новость')], default='promo', max_length=20, verbose_name='Тип анонса'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
