# Generated by Django 5.0.6 on 2025-02-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_announcement_options_announcement_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.CreateModel(
            name='AnnouncementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='star', help_text='Например: star, gift, calendar', max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.announcement', verbose_name='Анонс')),
            ],
            options={
                'verbose_name': 'Элемент анонса',
                'verbose_name_plural': 'Элементы анонса',
                'ordering': ['order'],
            },
        ),
    ]
