# Generated by Django 5.0.6 on 2025-02-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_announcement_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementitem',
            name='icon',
        ),
    ]
