# Generated by Django 5.0.6 on 2025-02-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_announcementitem_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки')),
                ('background_image', models.ImageField(upload_to='hero/', verbose_name='Фоновое изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Hero секция',
                'verbose_name_plural': 'Hero секции',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.city', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='AnnouncementMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/', verbose_name='Медиафайл')),
                ('is_video', models.BooleanField(default=False, verbose_name='Это видео')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.announcement', verbose_name='Анонс')),
            ],
            options={
                'verbose_name': 'Медиафайл анонса',
                'verbose_name_plural': 'Медиафайлы анонса',
                'ordering': ['order'],
            },
        ),
    ]
