# Generated by Django 5.0.6 on 2025-02-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_homehero_announcement_city_announcementmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homehero',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='homehero',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='homehero',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='homehero',
            name='title',
        ),
    ]
