# Generated by Django 5.1.6 on 2025-02-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_homehero_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_theme_logo', models.ImageField(upload_to='logos/', verbose_name='Логотип для светлой темы')),
                ('dark_theme_logo', models.ImageField(upload_to='logos/', verbose_name='Логотип для темной темы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Логотип сайта',
                'verbose_name_plural': 'Логотипы сайта',
            },
        ),
    ]
