# Generated by Django 5.0.6 on 2025-02-08 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_sitelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название заведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
                'ordering': ['order', 'name'],
            },
        ),
    ]
