# Generated by Django 5.1.6 on 2025-02-08 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_photoalbum_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoalbum',
            name='venue',
        ),
        migrations.AlterModelOptions(
            name='photoalbum',
            options={'ordering': ['-date', 'order'], 'verbose_name': 'Фотоальбом', 'verbose_name_plural': 'Фотоальбомы'},
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_albums', to='main.brand', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='yandex_preview_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='yandex_folder',
            field=models.CharField(help_text='Укажите путь к папке на Яндекс.Диске (например: Photos/Events/2024)', max_length=200, verbose_name='Папка на Яндекс.Диске'),
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
