# Generated by Django 5.0.6 on 2025-02-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_photographer_remove_photoalbum_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='albums/covers/', verbose_name='Обложка'),
        ),
    ]
