# Generated by Django 5.0 on 2025-02-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_photoalbum_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topgalleryimage',
            options={'verbose_name': 'Изображение галереи', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='topgalleryimage',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.brand'),
        ),
        migrations.AlterField(
            model_name='topgalleryimage',
            name='image',
            field=models.ImageField(upload_to='brands/gallery/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='BottomGalleryImage',
        ),
    ]
